#!/usr/bin/env bash
set -eux
NAME=grpc-fastcgi-proxy
ARCH=amd64

export GOFLAGS=-mod=vendor

for OS in darwin linux; do
    FILE=${NAME}.${OS}.${ARCH}
    CGO_ENABLED=0 GOOS=${OS} GOARCH=${ARCH} go build -o ${FILE} ./cmd/${NAME}
done
